-- Smash Burger Tracker — initial schema
--
-- Access model: PUBLIC READ, PRIVATE WRITE. Anyone with the URL can see the
-- leaderboard; only signed-in users can add or change anything. There is no
-- per-crew tenancy column, because there is one shared dataset — "who may
-- write" is answered by "does this person have an account", and sign-ups are
-- disabled in the dashboard so accounts are created by hand.
--
-- Run this in the Supabase dashboard: SQL Editor → New query → paste → Run.

-- ---------------------------------------------------------------------------
-- Rating values
-- ---------------------------------------------------------------------------
-- 1.0 to 5.0 in half-point steps. Until now this rule lived only in the rating
-- UI, which means anything writing to the database by another route could
-- store 3.7 and silently skew a burger's average. A domain puts it where it
-- cannot be bypassed. (`VALUE` is the domain's own keyword, not the `value`
-- column that happens to use this type.)
create domain public.rating_value as numeric(2, 1)
  check (VALUE >= 1.0 and VALUE <= 5.0 and (VALUE * 2) = trunc(VALUE * 2));

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
-- Ids are `text`, not `uuid`, and are generated by the client (`lib/id.ts`).
-- Two reasons: `newId()` falls back to non-UUID formats when crypto.randomUUID
-- is unavailable, and Phase 4's offline mode needs a client to mint an id for
-- a burger logged with no signal, long before the row reaches Postgres. The
-- database is not the id authority here.

create table public.reviewers (
  id          text primary key,
  name        text not null check (length(trim(name)) > 0),
  created_at  timestamptz not null default now()
);

create table public.visits (
  id               text primary key,
  restaurant_name  text not null,
  burger_name      text not null,
  location         text not null default '',
  -- A calendar date, not a timestamp. Postgres `date` comes back over the wire
  -- as a plain 'YYYY-MM-DD' string, which is exactly what `formatDate` expects
  -- and why the app's "renders as the previous day west of Greenwich" bug
  -- cannot come back through this column.
  date             date not null,
  price            numeric(10, 2),
  notes            text not null default '',
  photo_id         text,
  created_at       timestamptz not null default now()
);

create table public.ratings (
  id               text primary key,
  visit_id         text not null references public.visits(id)    on delete cascade,
  reviewer_id      text not null references public.reviewers(id) on delete cascade,
  smash_texture    public.rating_value not null,
  beef_flavor      public.rating_value not null,
  cheese_toppings  public.rating_value not null,
  bun              public.rating_value not null,
  value            public.rating_value not null,
  -- One scorecard per person per burger.
  unique (visit_id, reviewer_id)
);

-- The cascades above are the database half of two rules the app already
-- enforces in `lib/mutations.ts`: deleting a burger takes its scorecards, and
-- deleting a reviewer takes theirs. Stated in both places on purpose — the app
-- needs it to update the screen, the database needs it so no other writer can
-- leave an orphaned rating quietly folded into a burger's average.

create index ratings_visit_id_idx    on public.ratings (visit_id);
create index ratings_reviewer_id_idx on public.ratings (reviewer_id);
create index visits_date_idx         on public.visits (date desc);

-- NOTE: there is deliberately no `score` column on either table, and there
-- must never be one. Scores are derived from the raw category ratings on read.
-- A stored score drifts out of sync the moment the category weights are
-- retuned. If you want scores in SQL, add a VIEW over these columns.

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- RLS is what makes it safe to ship the anon key inside the JavaScript bundle.
-- The key identifies the project, it does not grant anything; these policies
-- are the only thing standing between a stranger and your data. Every table
-- below must have RLS enabled — a table without it is world-writable.

alter table public.reviewers enable row level security;
alter table public.visits    enable row level security;
alter table public.ratings   enable row level security;

-- Public read: no `to` clause, so this covers anon and authenticated alike.
create policy "anyone can read reviewers" on public.reviewers for select using (true);
create policy "anyone can read visits"    on public.visits    for select using (true);
create policy "anyone can read ratings"   on public.ratings   for select using (true);

-- Private write: `to authenticated` is the whole access check. Because
-- sign-ups are disabled, having an account IS the allowlist.
create policy "signed-in users can add reviewers"    on public.reviewers for insert to authenticated with check (true);
create policy "signed-in users can edit reviewers"   on public.reviewers for update to authenticated using (true) with check (true);
create policy "signed-in users can delete reviewers" on public.reviewers for delete to authenticated using (true);

create policy "signed-in users can add visits"    on public.visits for insert to authenticated with check (true);
create policy "signed-in users can edit visits"   on public.visits for update to authenticated using (true) with check (true);
create policy "signed-in users can delete visits" on public.visits for delete to authenticated using (true);

create policy "signed-in users can add ratings"    on public.ratings for insert to authenticated with check (true);
create policy "signed-in users can edit ratings"   on public.ratings for update to authenticated using (true) with check (true);
create policy "signed-in users can delete ratings" on public.ratings for delete to authenticated using (true);

-- ---------------------------------------------------------------------------
-- Table privileges
-- ---------------------------------------------------------------------------
-- Required because the project is created with "Automatically expose new
-- tables" turned OFF. In that mode a new table in `public` gets no privileges
-- for the Data API roles, so PostgREST answers "permission denied" until it is
-- granted explicitly here.
--
-- That is the safer default and worth the extra lines: a table someone adds
-- later and forgets to think about is invisible rather than world-readable.
-- The cost is that every future table needs its own grants, right here.
--
-- Two independent gates, both of which must pass: GRANT decides whether a role
-- may touch the table at all, RLS decides which rows. Granting without a policy
-- returns nothing; a policy without a grant returns "permission denied".

grant usage on schema public to anon, authenticated;

-- Domains default to PUBLIC usage; stated explicitly so a locked-down project
-- cannot fail inserts with a confusing type-permission error.
grant usage on type public.rating_value to anon, authenticated;

-- Anonymous visitors read the leaderboard and nothing more.
grant select on public.reviewers, public.visits, public.ratings to anon;

-- Signed-in crew members get full write access, gated by the policies above.
grant select, insert, update, delete
  on public.reviewers, public.visits, public.ratings
  to authenticated;

-- ---------------------------------------------------------------------------
-- Photo storage
-- ---------------------------------------------------------------------------
-- Public bucket, because anonymous visitors have to be able to load the
-- photos on a leaderboard they can already read. Anything in here is readable
-- by anyone who has the URL, so this bucket holds burger photos and nothing
-- else.
insert into storage.buckets (id, name, public)
values ('burger-photos', 'burger-photos', true)
on conflict (id) do nothing;

create policy "signed-in users can upload burger photos"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'burger-photos');

create policy "signed-in users can replace burger photos"
  on storage.objects for update to authenticated
  using (bucket_id = 'burger-photos') with check (bucket_id = 'burger-photos');

create policy "signed-in users can delete burger photos"
  on storage.objects for delete to authenticated
  using (bucket_id = 'burger-photos');
